apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nproject-backend-canary
  namespace: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'pg-app'
        vault.hashicorp.com/agent-inject-secret-pg-config: 'secret/pg-prod'
        vault.hashicorp.com/agent-inject-template-pg-config: |
          {{- with secret "secret/pg-prod" }}
          export DB_USER="{{ .Data.data.username }}"
          export DB_PASSWORD="{{ .Data.data.password }}"
          export DB_HOST="{{ .Data.data.host }}"
          {{- end }}
    spec:
      serviceAccountName: nproject-sa
      containers:
      - name: backend
        image: 85.208.87.35:5000/nproject-backend:40
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "=== Starting Backend Initialization ==="
            if [ -f /vault/secrets/pg-config ]; then
              echo "Secrets file found. Loading variables..."
              source /vault/secrets/pg-config
              echo "DB_HOST is set to: $DB_HOST"
              echo "Starting Uvicorn server..."
              uvicorn main:app --host 0.0.0.0 --port 8000
            else
              echo "ERROR: Secrets file NOT found at /vault/secrets/pg-config"
              echo "Listing /vault/secrets directory:"
              ls -la /vault/secrets/
              exit 1
            fi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
  
  # Canary стратегия
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate-check
      steps:
      - setWeight: 20        # 20% трафика на canary
      - pause: {duration: 2m} # Ждём 2 минуты
      - analysis:                           # ← Запускаем проверку
          templates:
          - templateName: success-rate-check
      - setWeight: 50        # 50% трафика
      - pause: {duration: 2m}
      - analysis:                           # ← Ещё раз проверяем
          templates:
          - templateName: success-rate-check
      - setWeight: 100       # 100% трафика → полная миграция